name: Analyze Diff

on:
  pull_request:

jobs:
  analyze_diff:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false
          lfs: true
      - name: Unity Build
        run: |
          # Unityのインストールディレクトリへのパスを環境変数に設定
          unityPath="/Applications/Unity/Hub/Editor/2022.2.21f1/Unity.app/Contents/MacOS/Unity"
          pwd
          # バッチモードで実行
          #$unityPath -batchmode -quit -logFile "build.log" -executeMethod Solution.DotnetProjectUtility.CreateProject
      - name: CleanLocalFiles
        run: |
          git reset --hard
          git clean -df
      - name: Analyze Diff
        run: git diff --stat origin/main ${{ github.event.pull_request.head.sha }}
